-- Add people-partners page to CMS
-- Run this in your Supabase SQL Editor

-- Insert the new people-partners page
INSERT INTO pages (
  slug,
  title,
  description,
  meta_title,
  meta_description,
  is_published,
  created_at,
  updated_at,
  created_by
) VALUES (
  'people-partners',
  'Partner Network',
  'Scale Your Execution with a Trusted Ecosystem of Specialized Firms - For large-scale initiatives, leverage our Partner Network—a curated ecosystem of specialized consulting firms and agencies that bring deep domain expertise and a full team of resources to solve your most complex challenges.',
  'Elevation AI Partner Network - Trusted Consulting Firms for Large-Scale Initiatives',
  'Scale your execution with our Partner Network of specialized consulting firms and agencies. Expert guidance for large-scale digital transformation, post-merger integration, and strategic initiatives.',
  true,
  NOW(),
  NOW(),
  (SELECT id FROM auth.users WHERE email = 'admin@elevationai.com' LIMIT 1)
) ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  meta_title = EXCLUDED.meta_title,
  meta_description = EXCLUDED.meta_description,
  updated_at = NOW();

-- Get the page ID for inserting sections
DO $$
DECLARE
  page_id_var UUID;
BEGIN
  -- Get the page ID
  SELECT id INTO page_id_var FROM pages WHERE slug = 'people-partners';
  
  -- Insert page sections for people-partners page
  INSERT INTO page_sections (
    page_id,
    section_type,
    section_order,
    title,
    section_data,
    is_published,
    created_at,
    updated_at
  ) VALUES 
  -- Hero Section
  (
    page_id_var,
    'hero_simple',
    1,
    'Hero Section',
    '{
      "title": "Scale Your Execution with a Trusted Ecosystem of Specialized Firms",
      "description": "For large-scale initiatives, leverage our Partner Network—a curated ecosystem of specialized consulting firms and agencies that bring deep domain expertise and a full team of resources to solve your most complex challenges.",
      "ctaButtons": [
        {
          "text": "Learn More",
          "href": "#challenge-solution",
          "variant": "default"
        },
        {
          "text": "Meet Our Partners",
          "href": "/website/demo",
          "variant": "outline"
        }
      ],
      "logoImage": "/images/branding/E-AI-Squircle.svg"
    }'::jsonb,
    true,
    NOW(),
    NOW()
  ),
  -- Challenge and Solution Section
  (
    page_id_var,
    'problem_cards',
    2,
    'Challenge and Solution',
    '{
      "challenge": {
        "badgeText": "The Challenge",
        "title": "The Disconnect of Traditional Consulting",
        "statement": "Large-scale projects often require the horsepower of a dedicated consulting firm. However, traditional engagements can be disjointed. External firms often work in their own systems, leading to siloed communication, a painful knowledge transfer process at the end of the project, and a lack of real integration with your team."
      },
      "solution": {
        "badgeText": "Our Solution: A Natively Integrated Partnership",
        "subtitle": "A New Model for Consulting Engagement",
        "description": "Our Partner Network consists of leading, highly specialized consulting firms who are experts on the Elevation AI platform. This creates a fundamentally better engagement model, providing a level of integrated expertise that a single expert cannot offer.",
        "processSteps": [
          {
            "title": "A Unified Workspace",
            "description": "Instead of working in separate systems, our partners embed directly into your Elevation AI Workspaces. This creates a single, shared environment for all communication, deliverables, and project management, providing you with unprecedented transparency.",
            "icon": "building-2-line"
          },
          {
            "title": "No Lost Knowledge",
            "description": "Because the entire engagement happens on your platform, all of the work product, research, and strategic insights generated by the consulting team are automatically captured in your private Knowledge Base. When the project ends, the knowledge stays with you.",
            "icon": "shield-check-line"
          },
          {
            "title": "Accelerated Execution",
            "description": "Our partners leverage our platform''s library of pre-built agents and workflows to deliver results faster. They spend less time on manual data gathering and more time on high-value strategic work, resulting in a more efficient and impactful engagement.",
            "icon": "zap-line"
          }
        ]
      }
    }'::jsonb,
    true,
    NOW(),
    NOW()
  ),
  -- Who This Is For Section
  (
    page_id_var,
    'approach_cards',
    3,
    'Who This Is For',
    '{
      "badgeText": "Who This Is For",
      "title": "Strategic Horsepower for Your Biggest Initiatives",
      "description": "Our Partner Network is ideal for organizations undertaking:",
      "logoImage": "/images/branding/E-AI-Sqaure.svg",
      "characteristics": [
        {
          "number": "1",
          "title": "Large-Scale Transformation",
          "description": "Large-scale digital or agentic transformation projects."
        },
        {
          "number": "2",
          "title": "Post-Merger Integration",
          "description": "Post-merger integration for a newly acquired company."
        },
        {
          "number": "3",
          "title": "New Market Entry",
          "description": "The rollout of a new product or entry into a new market."
        },
        {
          "number": "4",
          "title": "Operational Overhaul",
          "description": "A comprehensive operational overhaul to prepare for an exit."
        }
      ]
    }'::jsonb,
    true,
    NOW(),
    NOW()
  ),
  -- Partner Network Carousel Section
  (
    page_id_var,
    'solutions_carousel',
    4,
    'Partner Network',
    '{
      "badgeText": "Partner Network",
      "title": "Trusted Consulting Partners",
      "description": "Our Partner Network consists of leading consulting firms and agencies that are experts on the Elevation AI platform, bringing deep domain expertise and full team resources to solve your most complex challenges.",
      "backgroundColor": "bg-green-500/10",
      "partnerCategories": [
        {
          "id": "digital-transformation",
          "title": "Digital Transformation",
          "description": "Strategic guidance on large-scale digital transformation initiatives and change management.",
          "icon": "building-2-line",
          "specialties": ["Strategy", "Change Management", "Implementation", "ROI Analysis"]
        },
        {
          "id": "merger-integration",
          "title": "Merger & Integration",
          "description": "Expert support for post-merger integration and organizational restructuring.",
          "icon": "shield-check-line",
          "specialties": ["Integration Planning", "Due Diligence", "Cultural Alignment", "System Integration"]
        },
        {
          "id": "market-expansion",
          "title": "Market Expansion",
          "description": "Strategic support for new market entry and product rollout initiatives.",
          "icon": "global-line",
          "specialties": ["Market Research", "Go-to-Market", "Partnership Development", "Launch Strategy"]
        },
        {
          "id": "exit-preparation",
          "title": "Exit Preparation",
          "description": "Comprehensive operational overhaul and preparation for successful exits.",
          "icon": "handshake-line",
          "specialties": ["Operational Excellence", "Financial Optimization", "Due Diligence Prep", "Value Maximization"]
        }
      ],
      "carouselSettings": {
        "autoPlay": true,
        "autoPlayInterval": 5000,
        "showProgressIndicators": true,
        "cardWidth": 320,
        "cardGap": 24,
        "highlightActiveCard": true,
        "naturalScroll": false,
        "flexibleWidth": true
      }
    }'::jsonb,
    true,
    NOW(),
    NOW()
  ),
  -- Logo Carousel Section
  (
    page_id_var,
    'logo_carousel',
    5,
    'Logo Carousel',
    '{
      "title": "Led by industry veterans from:",
      "backgroundColor": "bg-muted/20"
    }'::jsonb,
    true,
    NOW(),
    NOW()
  ),
  -- CTA Section
  (
    page_id_var,
    'cta',
    6,
    'Call to Action',
    '{
      "title": "Find the Right Partner for Your Next Big Move",
      "description": "Discover our ecosystem of trusted consulting firms and agencies.",
      "backgroundColor": "bg-muted/30",
      "ctaButtons": [
        {
          "text": "Meet Our Partners",
          "href": "/website/demo",
          "variant": "default"
        },
        {
          "text": "About Us",
          "href": "/website/about",
          "variant": "outline"
        }
      ]
    }'::jsonb,
    true,
    NOW(),
    NOW()
  );

END $$;

-- Success message
SELECT 'People Partners page successfully created in CMS!' as message;
